### ISSUE TITLE
c+k ⚄♱⚁

### ISSUE THREAD

**Issue by ifsiee** [ifsiee/Message#3]
new chat <3

**Comment by ifsia** [comment]
hey my love, im sweating again. i woke up and saw that you called im really sorry i fell asleep i dont remember it really either again. i hope you're doing alright. are you mad also? i thought maybe you'd text on here or a goodnight but its okay. just know youre always in my mind and heart and im praying for you. love you kitsune.

**Comment by ifsia** [comment]
https://github.com/ifsiee/Message/assets/155914640/310b2b38-cf62-4d1d-a1c6-14a97cfa2e6d

**Comment by ifsia** [comment]
good morning

**Comment by ifsiee** [comment]
> hey my love, im sweating again. i woke up and saw that you called im really sorry i fell asleep i dont remember it really either again. i hope you're doing alright. are you mad also? i thought maybe you'd text on here or a goodnight but its okay. just know youre always in my mind and heart and im praying for you. love you kitsune.

noooo i didnt mean to, i was still typing on the other one ☠ i forgot, i love you sm

**Comment by ifsiee** [comment]
thank you babe, youre the best

**Comment by ifsiee** [comment]
i tried to login to snap on desi´s phone but it didnt let me

**Comment by ifsiee** [comment]
why havent you texted?

**Comment by ifsia** [comment]
i thought you didnt want to talk

**Comment by ifsia** [comment]
im too fucked uob ibwanna die

**Comment by ifsiee** [comment]
what happen, did you take something

**Comment by ifsiee** [comment]
> i thought you didnt want to talk

ofc i did,you literally saw my messages on the other note. and ive been texting on here numerous times on here since i found it.

**Comment by ifsiee** [comment]
you better not have relapsed i stg

**Comment by ifsiee** [comment]
also i had another therapy session after school i had to go to, i put you on my saftey plan.

**Comment by ifsiee** [comment]
what did you take. you fucking promised me

**Comment by ifsiee** [comment]
answer me

**Comment by ifsiee** [comment]
tell me what you fucking took

**Comment by ifsiee** [comment]
answer your scaring me

**Comment by ifsiee** [comment]
answwer

**Comment by ifsiee** [comment]
CHRISTIAN ANSWER

**Comment by ifsiee** [comment]
pleasee im crying did you relapse

**Comment by ifsiee** [comment]
please answer

**Comment by ifsiee** [comment]
anwser mw

**Comment by ifsiee** [comment]
ANSWER MNE

**Comment by ifsiee** [comment]
pleaase im scared pleaaww answer

**Comment by ifsiee** [comment]
please dont relapse pleasde pleasedp please

**Comment by ifsiee** [comment]
please

**Comment by ifsiee** [comment]
im freaking out answer please

**Comment by ifsiee** [comment]
im getting my phone from dad to call mom. you better tell me what tf you took

**Comment by ifsia** [comment]
a case

**Comment by ifsia** [comment]
no pills baby

**Comment by ifsia** [comment]
im sorry i scared you i miss you a lot

**Comment by ifsiee** [comment]
i miss you more, i wanted to call you but dad was sitting at the end of the bed when i was on the phone with mom

**Comment by ifsiee** [comment]
i hope you see this and we can both stay in the chat and talk because i really miss you

**Comment by ifsiee** [comment]
maybe zoom?

**Comment by ifsiee** [comment]
im getting in bath, ill text you at 10;10 ish, i love you so much!!

**Comment by ifsiee** [comment]
hey baby, im guessing youre sleeping. im prob going to watch some youtube or something so ill check here again a few times and lyk when i go to sleep. 
i love you so much christian and i missed you sm today. i kept crying cause i miss my baby boy and i cant live without you. 
Youre the bestest bf ever and i thank you for waiting for me (: 
ill forever wait for you and i love you forever ending. Always. No Matter What. 
Ill be here by your side until the end. we have a bright future together christian. We will do great things together. Cant wait to get my phone back (: 
im calling mom around 3 on my phone, ill try to text/call then (5 your time) so have ringer on. 
Also lets zoom tomorrow. ill lyk a time in the morning. 
I cant wait to get married.
I hope youre dreaming of me (: 
sweet dreams, sleep tight. 
Goodnight my love 🩷

**Comment by ifsiee** [comment]
also im going to sleep now because zookie is asleep and i wanna be responsible like you, 
i love you forever ending, never forget. 
ill text you when i wakeupppp (: 
🩷🩵 <<<--- us (also lmk if you can see emojis)
(●’3)♡(ε`●)
im so inlove with you
okayyy, sleep so good, dream of us, mwauhhhhhhhh
mwauh mwauh, kisses, besos, text me when you wakeup, and i miss youuuu
zoom tomorrowwww!!!!

**Comment by ifsiee** [comment]
goodmorning

**Comment by ifsiee** [comment]
hello????

**Comment by ifsiee** [comment]
are you ignoring me

**Comment by ifsiee** [comment]
hello??

**Comment by ifsiee** [comment]
i miss you

**Comment by ifsia** [comment]
good morning kitsu. i was really hungover and missed my exam for chem. still passed with a 67! i took a shower and got ready. nana mad at me so she got me doing chores. im really sorry kitsu. i miss you a loy and ive been declining. i really need you

**Comment by ifsia** [comment]
i love you bunches my sweet baby

**Comment by ifsia** [comment]
🩵🩷

**Comment by ifsia** [comment]
i really appreciate the paragraphs baby i love them so much

**Comment by ifsiee** [comment]
> good morning kitsu. i was really hungover and missed my exam for chem. still passed with a 67! i took a shower and got ready. nana mad at me so she got me doing chores. im really sorry kitsu. i miss you a loy and ive been declining. i really need you

please wait for me and make good choices, if you want to drink or anything else bad listen to our playists and photos of us<33
I want you happy and healthy and i might get my phone back this coming week!!! so be excitedddd

**Comment by ifsiee** [comment]
alsooooo, im getting my phone in a few minutes to call mommmmmm, ill text you as much as i can and try to snap/ call

**Comment by ifsiee** [comment]
be a good boy for me baby, im very worried about my boy. 
i love you dearly. xoxo 🩷

**Comment by ifsia** [comment]
yes maam i love you lots

**Comment by ifsiee** [comment]
hiiiiii

**Comment by ifsiee** [comment]
dad left my mom in here but he just came in and took it

**Comment by ifsiee** [comment]
phone*** mb mom is on my mind ☠

**Comment by ifsiee** [comment]
> i really appreciate the paragraphs baby i love them so much

good!!! i had to type queitly

**Comment by ifsiee** [comment]
try to check github every 5 minutes when we are talking please, if we arent just every few hours

**Comment by ifsiee** [comment]
hello?

**Comment by ifsiee** [comment]
!!

**Comment by ifsiee** [comment]
hello?

**Comment by ifsiee** [comment]
ill just wait and stop sending messages,not like they notify you or anything

**Comment by ifsia** [comment]
i dont know how to enable them kitsu

**Comment by ifsia** [comment]
i tried looking for it in settings

**Comment by ifsia** [comment]
im not tryna upset you or ignore you my bad

**Comment by ifsiee** [comment]
no its fine its just that i texted you mutliple times that i was going to text you on here when i was done, i was talking to a lawyer

**Comment by ifsiee** [comment]
im sorry i texted a few minutes after i said i would, i just thought you were going to be checking

**Comment by ifsiee** [comment]
i hope you see these texts soon atleast

**Comment by ifsiee** [comment]
also i took a bath thats why it took me 20 to respond

**Comment by ifsia** [comment]
its okay im sorry im tryna get the notifications for dis shi

**Comment by ifsiee** [comment]
i love you sm, dad going to store. can you check the location to see if its here??

**Comment by ifsiee** [comment]
on my phone

**Comment by ifsiee** [comment]
idk if he took it with him

**Comment by ifsiee** [comment]
??

**Comment by ifsiee** [comment]
no fucking way

**Comment by ifsiee** [comment]
![IMG_20240111_183334](https://github.com/ifsiee/Message/assets/155914529/26246783-c963-451b-9253-a6a0fd48dc8e)

old ipod, pray it works

**Comment by ifsiee** [comment]
![IMG_20240111_183432](https://github.com/ifsiee/Message/assets/155914529/414c2a0a-c646-4629-a131-a130c3ba1357)
iphone 7

**Comment by ifsia** [comment]
your phone still at the house

**Comment by ifsia** [comment]
CHARGEEE

**Comment by ifsiee** [comment]
zoom???

**Comment by ifsiee** [comment]
> your phone still at the house

ill look

**Comment by ifsiee** [comment]
zoom??

**Comment by ifsiee** [comment]
THERES A PASSWORD ON THE IPHONE 7 but its on
zoom me fast and help babe

**Comment by ifsiee** [comment]
HURRY

**Comment by ifsiee** [comment]
IPHONE LIKE 2 IS ON AND OPEN HURRY

**Comment by ifsiee** [comment]
TJIS PHONE AINT BEEN OPEN SINCE 2018 IT STILL HAS TABS OPEN

**Comment by ifsiee** [comment]
nevermind dads home now

**Comment by ifsiee** [comment]
also ima put the phones back, i cant do it without help

**Comment by ifsiee** [comment]
getting my phone to call mom in a second

**Comment by ifsiee** [comment]
i need to go to her house to get my stuff, also send me your number i need to write it down and ill try to ft you from my friends phones or some

**Comment by ifsiee** [comment]
mom said im not allowed the xbox though

**Comment by ifsia** [comment]
8032888576

**Comment by ifsiee** [comment]
why are you so dry, ive sent sm messages, you didnt even say anything about zoom??? confused.

**Comment by ifsiee** [comment]
also dont reaspons to texts, dad has phone i delete my chats so if you respond to those specificly then he will know i texted, and i also started crying and told him i miss you

**Comment by ifsiee** [comment]
going to moms, check github at 8:30 and 9:30, lets try to zoom at 9:45

**Comment by ifsiee** [comment]
i love you forever ending, ima try to find and bring my old ipad

**Comment by ifsia** [comment]
i love you more forever ending im jus so exhausted kitsu im sorry if i seem dry. im hurting bad

**Comment by ifsia** [comment]
hello

**Comment by ifsia** [comment]
i love you kitsu

**Comment by ifsia** [comment]
im waiting to zoom

**Comment by ifsia** [comment]
kitsu this is too hard

**Comment by ifsiee** [comment]
baby i said i was going to moms silly

**Comment by ifsiee** [comment]
i got all my stuff, i told you i was going to moms. i wanted to zoom over 2 hours ago love

**Comment by ifsiee** [comment]
> kitsu this is too hard

are you leaving me?? why cant you wait

**Comment by ifsiee** [comment]
can we zoom now?

**Comment by ifsiee** [comment]
i just got home

**Comment by ifsiee** [comment]
wdym this is to hard

**Comment by ifsiee** [comment]
im on zoom, waiting

**Comment by ifsiee** [comment]
please respond

**Comment by ifsiee** [comment]
eatting soup ill text you after

**Comment by ifsiee** [comment]
10 minish

**Comment by ifsiee** [comment]
hi

**Comment by ifsiee** [comment]
i miss you

**Comment by ifsia** [comment]
i miss you more

**Comment by ifsia** [comment]
how do i join the meet

**Comment by ifsiee** [comment]
are you still there? i went out to dinner room, i didnt think youd answerr

**Comment by ifsiee** [comment]
im here now

**Comment by ifsiee** [comment]
im sorry baby please still be there

**Comment by ifsiee** [comment]
please i really wanna zoom

**Comment by ifsia** [comment]
im here tell me how to do it

**Comment by ifsiee** [comment]
go on zoom

**Comment by ifsiee** [comment]
lmk when you need the code and password

**Comment by ifsiee** [comment]
??

**Comment by ifsia** [comment]
im in bed can i do it on the phone ?

**Comment by ifsiee** [comment]
maybe

**Comment by ifsiee** [comment]
did you try?

**Comment by ifsia** [comment]
i have it downloaded

**Comment by ifsiee** [comment]
okay do you need code

**Comment by ifsiee** [comment]
?

**Comment by ifsiee** [comment]
are you starting it?

**Comment by ifsiee** [comment]
also lets stay in the chat, responses are long

**Comment by ifsiee** [comment]
babyyyy

**Comment by ifsiee** [comment]
i can start the zoom when youre ready (:

**Comment by ifsiee** [comment]
also im here now to respond asap

**Comment by ifsiee** [comment]
bubby i miss you ):

**Comment by ifsia** [comment]
im readt

**Comment by ifsiee** [comment]
YAY

**Comment by ifsiee** [comment]
meeting Id
981 5636 3415

**Comment by ifsiee** [comment]
https://zoom.us/j/98156363415?pwd=UklUc25lV0tianZMc2VaY2haSFVWUT09

**Comment by ifsiee** [comment]
here

**Comment by ifsiee** [comment]
joinnnnnnn

**Comment by ifsiee** [comment]
hurry hurry im so excited

**Comment by ifsiee** [comment]
joiinnn

**Comment by ifsiee** [comment]
babe?

**Comment by ifsia** [comment]
okay okay

**Comment by ifsiee** [comment]
are you joining?

**Comment by ifsiee** [comment]
babe?

**Comment by ifsiee** [comment]
ive been on the zoom for 25

**Comment by ifsia** [comment]
make another link its not working

**Comment by ifsiee** [comment]
ill send the code and password instead

**Comment by ifsia** [comment]
okay

**Comment by ifsiee** [comment]
meeting id: 938 9280 1117

**Comment by ifsiee** [comment]
password: dY8UqL

**Comment by ifsia** [comment]
no such meeting

**Comment by ifsiee** [comment]
i copied and pasted it

**Comment by ifsia** [comment]
ifsia has invited you to join a video meeting on Google Meet.

Join the meeting: https://meet.google.com/mvm-tvsy-mpv

**Comment by ifsiee** [comment]
![Screenshot 2024-01-11 11 23 07 PM](https://github.com/ifsiee/Message/assets/155914529/9f7df0ec-11b4-45ab-948e-e374f05f90a5)

**Comment by ifsiee** [comment]
i think we both have to be on computer

**Comment by ifsia** [comment]
are you serious

**Comment by ifsiee** [comment]
i think

**Comment by ifsiee** [comment]
get on and send zoom link

**Comment by ifsia** [comment]
ifsia has invited you to join a video meeting on Google Meet.

Join the meeting: https://meet.google.com/mvm-tvsy-mpv

**Comment by ifsiee** [comment]
babe. it doesnt work

**Comment by ifsiee** [comment]
get on computer and send zoom link

**Comment by ifsia** [comment]
bru.

**Comment by ifsiee** [comment]
what

**Comment by ifsia** [comment]
goodnight kitsu have a good night

**Comment by ifsia** [comment]
i love you

**Comment by ifsiee** [comment]
babe what

**Comment by ifsiee** [comment]
please dont go please

**Comment by ifsiee** [comment]
i need to zoom please

**Comment by ifsiee** [comment]
please

**Comment by ifsiee** [comment]
please stop im freaking out now why are you leaving

**Comment by ifsiee** [comment]
please zoom me

**Comment by ifsiee** [comment]
please dont go i need you really bad

**Comment by ifsia** [comment]
we cant even call after so long

**Comment by ifsiee** [comment]
please

**Comment by ifsiee** [comment]
please computer zoom please

**Comment by ifsiee** [comment]
ill do anything

**Comment by ifsiee** [comment]
please

**Comment by ifsiee** [comment]
please get on and send link please

**Comment by ifsiee** [comment]
i NEED you rn

**Comment by ifsiee** [comment]
please

**Comment by ifsiee** [comment]
please

**Comment by ifsiee** [comment]
please get on

**Comment by ifsiee** [comment]
lmk when your on computer and ill send the link

**Comment by ifsiee** [comment]
are you on?

**Comment by ifsia** [comment]
im in bed kitsu. its 1:34

**Comment by ifsia** [comment]
hopefully i can see you tmr

**Comment by ifsiee** [comment]
PLEASE BABY

**Comment by ifsiee** [comment]
please for me

**Comment by ifsia** [comment]
we have tmr hopefully

**Comment by ifsia** [comment]
goodnight kitsu

**Comment by ifsiee** [comment]
christian please

**Comment by ifsiee** [comment]
im having a breakdown please

**Comment by ifsiee** [comment]
please i feel like your leaving please

**Comment by ifsiee** [comment]
please just this once

**Comment by ifsiee** [comment]
please i promise i wont bother you anymore just please

**Comment by ifsiee** [comment]
please i actually need you in begging

**Comment by ifsiee** [comment]
im getting those things please

**Comment by ifsia** [comment]
im sorry kitsu but im just too exhausted. i wanted to earlier today not in the middle of the night. you can go a night without. goodnight take care love

**Comment by ifsiee** [comment]
NO PLEASE

**Comment by ifsiee** [comment]
im about to get up and ask dad for phone

**Comment by ifsiee** [comment]
please

**Comment by ifsiee** [comment]
Please just for a minute

**Comment by ifsia** [comment]
ill wait kitsu. i know you can also. lets sleep

**Comment by ifsiee** [comment]
please christian

**Comment by ifsiee** [comment]
NO PLEASE

**Comment by ifsiee** [comment]
i cant christian please

**Comment by ifsiee** [comment]
please christian

**Comment by ifsiee** [comment]
please please

**Comment by ifsia** [comment]
kitsu i cant. not even because im tired but because of oma too. it is 1:40

**Comment by ifsiee** [comment]
no please

**Comment by ifsiee** [comment]
christian i need you rn i cant

**Comment by ifsiee** [comment]
im actually freaking out please

**Comment by ifsiee** [comment]
please i need help i need you

**Comment by ifsiee** [comment]
please im scare

**Comment by ifsiee** [comment]
please im begging you

**Comment by ifsia** [comment]
i am too kitsu

**Comment by ifsiee** [comment]
i wouldnt make you go against oma is it wasnt emergency

**Comment by ifsiee** [comment]
im serious christian please

**Comment by ifsiee** [comment]
if not im going to find my phone or wake up dad or steal paschas phone to call you

**Comment by ifsiee** [comment]
its that important rn

**Comment by ifsiee** [comment]
im serious please

**Comment by ifsia** [comment]
dont. theres no need to when we have tomorrow morning. me and you both need sleep. i love you

**Comment by ifsiee** [comment]
no please

**Comment by ifsiee** [comment]
christian im trying to not hurt myself

**Comment by ifsiee** [comment]
PLEASE

**Comment by ifsiee** [comment]
please

**Comment by ifsiee** [comment]
this is an emergency why wont you help

**Comment by ifsiee** [comment]
please

**Comment by ifsia** [comment]
kitsu why do you do me like this

**Comment by ifsiee** [comment]
christian i just need you rn please

**Comment by ifsia** [comment]
i needed you all the time

**Comment by ifsiee** [comment]
im going to get paschas phone.

**Comment by ifsiee** [comment]
i actually cant

**Comment by ifsiee** [comment]
goodmorning lover, i just woke up for school. youre prob already at school, i thought youd text!
i love you forever ending, have a great day

**Comment by ifsiee** [comment]
i hope schools going great!!!

**Comment by ifsiee** [comment]
or if you didnt go i hope your day is great

**Comment by ifsia** [comment]
i just woke up. we dont have school today or monday

**Comment by ifsiee** [comment]
yayyy!!

**Comment by ifsiee** [comment]
lets try to zoom todayyy

**Comment by ifsiee** [comment]
i miss you sm

**Comment by ifsia** [comment]
idk. i might just sleep today

**Comment by ifsiee** [comment]
okay, i would love if we could but its up to you!! we can actually talk this time, but ik you need rest

**Comment by ifsiee** [comment]
i love you forever ending

**Comment by ifsiee** [comment]
its almost lunch, we can text  when i get in english so check github in about 45-55 min (:

**Comment by ifsiee** [comment]
im sorry about last night btw

**Comment by ifsiee** [comment]
lunch time!

**Comment by ifsia** [comment]
yayy

**Comment by ifsiee** [comment]
do you not wanna say i love you back? you ignored it twice 😪 prob on accidenttt
but im in english now, i love you forever ending

**Comment by ifsiee** [comment]
i love youuu, dance time

**Comment by ifsia** [comment]
i love you so much kitsu im sorry i didnt see it baby please dont think tha way im really sorry

**Comment by ifsia** [comment]
i love you lots baby theres another storm

**Comment by ifsia** [comment]
hey, i might not respond imma be downstairs for a little bit because of the storm. i hope you youre okay. im just anxious. i love you

**Comment by ifsia** [comment]
https://github.com/ifsiee/Message/assets/155914640/c8aff883-d840-477a-a5ef-ebdb01bedb20

**Comment by ifsia** [comment]
https://github.com/ifsiee/Message/assets/155914640/486e2042-9703-4ff3-8092-da3faee07c2b

**Comment by ifsiee** [comment]
YOU BETTER NOT HAVE POSTED THOSE I STG YOU LOOK TO GOOD
also i love you sm, the storm willl pass. ill try to check here as much, aunt jen is coming over
i love you so muchhhhhhhhhhhh

**Comment by ifsia** [comment]
but i dont look good

**Comment by ifsia** [comment]
i love you more kitsu i hope you have fun.

**Comment by ifsia** [comment]
imma have the guys over

**Comment by ifsiee** [comment]
did you post? also no drinming or anything

**Comment by ifsiee** [comment]
why hangout but not zoom me?

**Comment by ifsiee** [comment]
its fine

**Comment by ifsia** [comment]
i thought you was busy? and i might have em over. we have to make Ds songs

**Comment by ifsia** [comment]
i didnt post

**Comment by ifsia** [comment]
i made you a video

**Comment by ifsia** [comment]
it wont let me upload it here

**Comment by ifsiee** [comment]
okay okay dont post, also not busy just aunt is here

**Comment by ifsiee** [comment]
also cant wait to see the video

**Comment by ifsia** [comment]
ill show you on zoom bubs :)

**Comment by ifsiee** [comment]
yayyy brb aunt talking

**Comment by ifsiee** [comment]
i love you sm

**Comment by ifsia** [comment]
i love you

**Comment by ifsiee** [comment]
i tried to get on phone to snap but dad came up

**Comment by ifsiee** [comment]
also me and aunt jen have been talking

**Comment by ifsia** [comment]
cool

**Comment by ifsiee** [comment]
im backkk

**Comment by ifsiee** [comment]
molly is coming over

**Comment by ifsiee** [comment]
are you mad, also did my snap send?

**Comment by ifsia** [comment]
yea it did

**Comment by ifsiee** [comment]
yayyy

**Comment by ifsiee** [comment]
did you leave me on opened again

**Comment by ifsia** [comment]
ion feel like theres a point when you dont got yo phone

**Comment by ifsiee** [comment]
okay, i still open them when i get my phone. ive looked for you messages and snapped but you havent sent any in days

**Comment by ifsiee** [comment]
its whateverrr i love you

**Comment by ifsiee** [comment]
id still like if youd send messages and snaps, shows me you care

**Comment by ifsiee** [comment]
((:

**Comment by ifsia** [comment]
okay bubs i jus didnt know if you wanted me to cuz you didnt say antthing last time. ill send snaps

**Comment by ifsia** [comment]
your thing acts weird too idk im jus overthinking stuff

**Comment by ifsia** [comment]
lets take a break while you dont have your phone. communicating on here is too stressing. i dont know what youre doin an things jus don align

**Comment by ifsiee** [comment]
no i dont want a break, just wait for me

**Comment by ifsiee** [comment]
wanna zoom

**Comment by ifsiee** [comment]
i tried to get dad to let me use phone to call you and he said no and i kepted asking and we got into arguement. i think im getting my phone back within the week. please just wait
i love you so much

**Comment by ifsiee** [comment]
i hope you sleep so well, sweet dreams and goodnight (: 
remember to think positive!
lets try and zoom tomorrow and if dad leaves ill try to take phone. 
dont unadd me or anything please (:

**Comment by ifsia** [comment]
okay

**Comment by ifsia** [comment]
goodngiht i love you kitsu.

**Comment by ifsia** [comment]
a lotta things jus ain makin sense an ion wanna have to worry about it.

**Comment by ifsia** [comment]
ion wanna continue this worrying. ion like was goin on wit you. i just feel like you ain truthful bout shi and im always one to go down. yu jus acting suspect and its hurtin me. i know its hard to talk but youve been doin things thas jus weird asf

**Comment by ifsiee** [comment]
ik love we havent had a lot of time to talk and im so sorry for that. tomorrow can we please try and zoom and ill show you what ive been doing cause im not allowed to go anywhere ☠😪 but posh said she MIGHT let me log into my snap on her phone, but shes letting me send a few you snaps of her phoneeee so thats good

**Comment by ifsiee** [comment]
also im sorry ive been acting weird,a lot has happened with mom and ill tell you on zoom or if pascha lets me use her phone. ive found out crazy things and im processing a lot. please wait for me baby boo, also sending snaps of pascha phone now

**Comment by ifsiee** [comment]
Look at messages and snap, goodnight bubba i love yoou forever ending <333

**Comment by ifsiee** [comment]
goodmorning love, i just woke up ☠
ihope your having a great day

**Comment by ifsia** [comment]
good morning i didnt sleep too good either i woke up too

**Comment by ifsia** [comment]
i love you kitsu

**Comment by ifsia** [comment]
its 4

**Comment by ifsiee** [comment]
hi baby i was sleepin again

**Comment by ifsiee** [comment]
zoom? i just woke up again
dad came in and said he was worried ☠

**Comment by ifsiee** [comment]
wait nevermind dad wants me to come out with him and posh
ill text you on here when i can but ill ask to use paschas phone! we are going to mollys for dinner

**Comment by ifsiee** [comment]
i love you sooo muchhh, i had a dream about you (: 
ill tell you about it when we talkkk <333
i love you forever ending

**Comment by ifsia** [comment]
okay have fun

**Comment by ifsiee** [comment]
are you on computer??

**Comment by ifsiee** [comment]
get on zoom rn

**Comment by ifsia** [comment]
im on the way home

**Comment by ifsia** [comment]
goodbye kitsu. youve been thru every moment in my life and i think youve done all you can. i really appreciate getting to spend time with you and grow up with you. maybe in the next one will we see each other again.i love you.
